<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robotic_arm_bringup</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="jim.gaganakis@gmail.com">dimitris-gkagkanakis</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <depend>robot_state_publisher</depend>
  <depend>joint_state_publisher</depend>
  <depend>joint_state_publisher_gui</depend>
  <depend>rviz2</depend>
  <depend>xacro</depend>
  <depend>robotic_arm_description</depend>
  <depend>ros_gz_sim</depend>
  <depend>ros2_control</depend>
  <depend>controller_manager</depend>
  <depend>robotic_arm_moveit_config</depend>
  <depend>robotic_arm_commander</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
